- name: Enable system services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    daemon_reload: true
  loop:
    - sddm
    - NetworkManager
    - bluetooth

- name: Enable user services (pipewire)
  become: false
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    scope: user
    daemon_reload: true
  loop:
    - pipewire
    - wireplumber
    - pipewire-pulse
