[colors.primary]
background = '#32302f'
foreground = '#ddc7a1'

[colors.cursor]
text = '#32302f'
cursor = '#ddc7a1'

[colors.vi_mode_cursor]
text = '#32302f'
cursor = '#a9b665'

[colors.search.matches]
foreground = '#3c3836'
background = '#89b482'

[colors.search.focused_match]
foreground = '#3c3836'
background = '#a9b665'

[colors.footer_bar]
foreground = '#3c3836'
background = '#e8e5e3'

[colors.hints.start]
foreground = '#3c3836'
background = '#e78a4e'

[colors.hints.end]
foreground = '#3c3836'
background = '#e78a4e'

[colors.selection]
text = '#ddc7a1'
background = '#504945'


[colors.normal]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#ddc7a1'


[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#ebdbb2'


[colors.dim]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#ddc7a1'
