---
- name: Install noctalia-shell AUR package
  kewlfft.aur.aur:
    name: noctalia-shell
    use: paru
  become: false

- name: Create wallpapers directory
  become: false
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Pictures/Wallpapers"
    state: directory

- name: Copy noctalia wallpaper
  become: false
  ansible.builtin.copy:
    src: cyberporsche.png
    dest: "{{ ansible_env.HOME }}/Pictures/Wallpapers/cyberporsche.png"
