---
- name: Install utility packages
  become: true
  ansible.builtin.package:
    name:
      - btop
      - fastfetch
      - fuzzel
      - nextcloud-client
      - noto-fonts
      - ranger
      - tree
      - zip

      - opencode
      - partitionmanager
      - pavucontrol
      - reflector
      - smartmontools
      - vim
      - wget
      - zram-generator
    state: present
