---
- name: Install official repo packages
  become: true
  ansible.builtin.pacman:
    name:
      - thunderbird
      - waydroid
      - flatpak
    state: present

- name: Install reaper (force overwrite due to manual install leftovers)
  become: true
  ansible.builtin.pacman:
    name: reaper
    state: present
    extra_args: --overwrite '*'

- name: Install Flatpak applications
  community.general.flatpak:
    name:
      - com.behringer.XAirEdit
    state: present
