- name: Configure localhost
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    install_grub_theme: true
    install_sddm_theme: true
    install_essential: true
    install_aur_leisure: true
    install_aur_work: false
    install_aur_noctalia: true
    install_gaming: false
    install_utils: true
    install_productivity: true
    install_ltr: true

  roles:

    - role:grub_theme
      when: install_grub_theme | bool

    - role: sddm_theme
      when: install_sddm_theme | bool
    
    - role: essential
      when: install_essential | bool

    - role: aur_leisure
      when: install_aur_leisure | bool

    - role: aur_work
      when: install_aur_work | bool

    - role: aur_noctalia
      when: install_aur_noctalia | bool

    - role: gaming
      when: install_gaming | bool

    - role: utils
      when: install_utils | bool

    - role: productivity
      when: install_productivity | bool

    - role: ltr
      when: install_ltr | bool
